version: "3"

services:
  frontend-books:
    container_name: frontend-books
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production